from typing import Any, Protocol

from agent_sdk.layer1_domain.entities.agent_registration import AgentRegistration


class IAgentRegistry(Protocol):
    async def register(self, registration: AgentRegistration) -> str: ...

    async def heartbeat(self, agent_id: str, status: str) -> None: ...

    async def deregister(self, agent_id: str) -> None: ...

    async def close(self) -> None: ...

    async def resolve_agent_id(self, agent_type: str) -> str | None: ...

    async def list_active_agents(self, domain: str | None = None) -> list[dict]: ...

    async def list_capabilities(self) -> list[dict[str, Any]]: ...

    async def get_queue_metadata(self, queue_name: str) -> dict[str, Any]: ...
