# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from . import push_gateway_pb2 as push__gateway__pb2

try:
    import grpc
except ImportError:
    grpc = None


class PushGatewayStub(object):
    def __init__(self, channel):
        if grpc is None:
            raise RuntimeError("grpcio is required for PushGatewayStub")

        self.SendData = channel.unary_unary(
            "/pushgateway.PushGateway/SendData",
            request_serializer=push__gateway__pb2.SendDataRequest.SerializeToString,
            response_deserializer=push__gateway__pb2.SendDataResponse.FromString,
            _registered_method=True,
        )
        self.SendDataStream = channel.stream_stream(
            "/pushgateway.PushGateway/SendDataStream",
            request_serializer=push__gateway__pb2.SendDataRequest.SerializeToString,
            response_deserializer=push__gateway__pb2.SendDataResponse.FromString,
            _registered_method=True,
        )


class PushGatewayServicer(object):
    def SendData(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendDataStream(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PushGatewayServicer_to_server(servicer, server):
    if grpc is None:
        raise RuntimeError("grpcio is required for PushGateway service registration")

    rpc_method_handlers = {
        "SendData": grpc.unary_unary_rpc_method_handler(
            servicer.SendData,
            request_deserializer=push__gateway__pb2.SendDataRequest.FromString,
            response_serializer=push__gateway__pb2.SendDataResponse.SerializeToString,
        ),
        "SendDataStream": grpc.stream_stream_rpc_method_handler(
            servicer.SendDataStream,
            request_deserializer=push__gateway__pb2.SendDataRequest.FromString,
            response_serializer=push__gateway__pb2.SendDataResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pushgateway.PushGateway", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
