# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push_gateway.proto
"""Generated protocol buffer code."""

try:
    from google.protobuf import descriptor_pb2 as _descriptor_pb2
    from google.protobuf import descriptor_pool as _descriptor_pool
    from google.protobuf import message_factory as _message_factory
    from google.protobuf import symbol_database as _symbol_database

    _sym_db = _symbol_database.Default()

    _file_proto = _descriptor_pb2.FileDescriptorProto()
    _file_proto.name = "push_gateway.proto"
    _file_proto.package = "pushgateway"
    _file_proto.syntax = "proto3"

    _message = _file_proto.message_type.add()
    _message.name = "SendDataRequest"
    _field = _message.field.add()
    _field.name = "key"
    _field.number = 1
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    _field = _message.field.add()
    _field.name = "data"
    _field.number = 2
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    _field = _message.field.add()
    _field.name = "is_final"
    _field.number = 3
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_BOOL

    _message = _file_proto.message_type.add()
    _message.name = "SendDataResponse"
    _field = _message.field.add()
    _field.name = "success"
    _field.number = 1
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_BOOL
    _field = _message.field.add()
    _field.name = "message"
    _field.number = 2
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    _field = _message.field.add()
    _field.name = "chunk_index"
    _field.number = 3
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_INT32
    _field = _message.field.add()
    _field.name = "is_final"
    _field.number = 4
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_BOOL

    _message = _file_proto.message_type.add()
    _message.name = "PersistedTopicData"
    _field = _message.field.add()
    _field.name = "key"
    _field.number = 1
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    _field = _message.field.add()
    _field.name = "state"
    _field.number = 2
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_STRING
    _field = _message.field.add()
    _field.name = "created_at"
    _field.number = 3
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE
    _field = _message.field.add()
    _field.name = "expires_at"
    _field.number = 4
    _field.label = _descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL
    _field.type = _descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE

    _service = _file_proto.service.add()
    _service.name = "PushGateway"
    _method = _service.method.add()
    _method.name = "SendData"
    _method.input_type = ".pushgateway.SendDataRequest"
    _method.output_type = ".pushgateway.SendDataResponse"
    _method = _service.method.add()
    _method.name = "SendDataStream"
    _method.input_type = ".pushgateway.SendDataRequest"
    _method.output_type = ".pushgateway.SendDataResponse"
    _method.client_streaming = True
    _method.server_streaming = True

    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
        _file_proto.SerializeToString()
    )

    SendDataRequest = _message_factory.GetMessageClass(
        DESCRIPTOR.message_types_by_name["SendDataRequest"]
    )
    SendDataResponse = _message_factory.GetMessageClass(
        DESCRIPTOR.message_types_by_name["SendDataResponse"]
    )
    PersistedTopicData = _message_factory.GetMessageClass(
        DESCRIPTOR.message_types_by_name["PersistedTopicData"]
    )

    _sym_db.RegisterMessage(SendDataRequest)
    _sym_db.RegisterMessage(SendDataResponse)
    _sym_db.RegisterMessage(PersistedTopicData)
except ImportError:
    DESCRIPTOR = None

    class _FallbackMessage:
        __slots__ = ()

        def SerializeToString(self) -> bytes:
            return repr(self).encode("utf-8")

        @classmethod
        def FromString(cls, _payload: bytes):
            return cls()

    class SendDataRequest(_FallbackMessage):
        __slots__ = ("key", "data", "is_final")

        def __init__(self, key: str = "", data: str = "", is_final: bool = False):
            self.key = key
            self.data = data
            self.is_final = is_final

    class SendDataResponse(_FallbackMessage):
        __slots__ = ("success", "message", "chunk_index", "is_final")

        def __init__(
            self,
            success: bool = False,
            message: str = "",
            chunk_index: int = 0,
            is_final: bool = False,
        ):
            self.success = success
            self.message = message
            self.chunk_index = chunk_index
            self.is_final = is_final

    class PersistedTopicData(_FallbackMessage):
        __slots__ = ("key", "state", "created_at", "expires_at")

        def __init__(
            self,
            key: str = "",
            state: str = "",
            created_at: float = 0.0,
            expires_at: float = 0.0,
        ):
            self.key = key
            self.state = state
            self.created_at = created_at
            self.expires_at = expires_at
