from typing import Protocol, TypeVar, List, Optional
T = TypeVar('T')


class IBaseRepository(Protocol[T]):
    async def find_all(self) -> List[T]: ...
    async def find_by_id(self, id: str) -> Optional[T]: ...
    async def save(self, entity: T) -> T: ...
    async def delete(self, id: str) -> bool: ...
