from typing import Protocol


class IRuntimeSettingRepository(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str) -> None: ...

    async def get_many(self, keys: list[str]) -> dict[str, str]: ...
