"""Logger interface for the agent registry application."""
from typing import Any, Protocol


class ILogger(Protocol):
    """Structured logger protocol. Infrastructure layer provides the concrete implementation.

    All methods accept an event name plus arbitrary keyword context fields
    (matching the AppLogger / structlog-style API).
    """

    def debug(self, event: str, *args: Any, **context: Any) -> None: ...
    def info(self, event: str, *args: Any, **context: Any) -> None: ...
    def log(self, event: str, *args: Any, **context: Any) -> None: ...
    def warning(self, event: str, *args: Any, **context: Any) -> None: ...
    def error(self, event: str, *args: Any, **context: Any) -> None: ...


class NullLogger:
    """No-op ILogger used as the default when none is injected (e.g. unit tests).

    Shared across every use case/service so the null-object pattern isn't re-declared
    in each module. Lives in the application layer (no infrastructure dependency), so
    use cases can default to it without importing anything from layer 4.
    """

    def debug(self, event: str, *args: Any, **context: Any) -> None: ...
    def info(self, event: str, *args: Any, **context: Any) -> None: ...
    def log(self, event: str, *args: Any, **context: Any) -> None: ...
    def warning(self, event: str, *args: Any, **context: Any) -> None: ...
    def error(self, event: str, *args: Any, **context: Any) -> None: ...