DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_DOCUMENTS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_DOCUMENTS" (
    "DOCUMENT_ID" NVARCHAR(64) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "SOURCE_FILE_ID" NVARCHAR(128) NOT NULL,
    "CONTENT_HASH" NVARCHAR(128) NOT NULL,
    "STATUS" NVARCHAR(32) NOT NULL,
    "DOC_TYPE" NVARCHAR(64) NOT NULL,
    "MIME_TYPE" NVARCHAR(255) NOT NULL,
    "FILENAME" NVARCHAR(512) NOT NULL,
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("DOCUMENT_ID", "TENANT_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_CHUNKS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_CHUNKS" (
    "CHUNK_ID" NVARCHAR(128) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "DOCUMENT_ID" NVARCHAR(64) NOT NULL,
    "SOURCE_FILE_ID" NVARCHAR(128) NOT NULL,
    "CONTENT_HASH" NVARCHAR(128) NOT NULL,
    "STATUS" NVARCHAR(32) NOT NULL,
    "DOC_TYPE" NVARCHAR(64) NOT NULL,
    "MIME_TYPE" NVARCHAR(255) NOT NULL,
    "PAGE_NO" INTEGER,
    "SHEET_NAME" NVARCHAR(255),
    "ROW_NUMBER" INTEGER,
    "CHUNK_KIND" NVARCHAR(64) NOT NULL DEFAULT ''semantic_text'',
    "CONTENT_FORMAT" NVARCHAR(32) NOT NULL DEFAULT ''text'',
    "TABLE_ID" NVARCHAR(128),
    "CONTENT" NCLOB NOT NULL,
    "METADATA_JSON" NCLOB,
    "PARENT_CONTEXT_ID" NVARCHAR(128),
    "EMBEDDING" REAL_VECTOR(640) NOT NULL,
    PRIMARY KEY ("CHUNK_ID", "TENANT_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_PARENT_CONTEXTS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_PARENT_CONTEXTS" (
    "PARENT_CONTEXT_ID" NVARCHAR(128) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "DOCUMENT_ID" NVARCHAR(64) NOT NULL,
    "CONTEXT_KIND" NVARCHAR(64) NOT NULL,
    "CONTENT" NCLOB NOT NULL,
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("PARENT_CONTEXT_ID", "TENANT_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_GRAPH_ENTITIES'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_GRAPH_ENTITIES" (
    "ENTITY_ID" NVARCHAR(128) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "DOCUMENT_ID" NVARCHAR(64),
    "CANONICAL_NAME" NVARCHAR(512) NOT NULL,
    "NORMALIZED_NAME" NVARCHAR(512),
    "ENTITY_TYPE" NVARCHAR(64) NOT NULL,
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("TENANT_ID", "ENTITY_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_GRAPH_RELATIONS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_GRAPH_RELATIONS" (
    "RELATION_ID" NVARCHAR(128) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "DOCUMENT_ID" NVARCHAR(64),
    "SOURCE_ENTITY_ID" NVARCHAR(128) NOT NULL,
    "TARGET_ENTITY_ID" NVARCHAR(128) NOT NULL,
    "RELATION_TYPE" NVARCHAR(128) NOT NULL,
    "CONFIDENCE" DOUBLE,
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("TENANT_ID", "RELATION_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_GRAPH_MENTIONS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_GRAPH_MENTIONS" (
    "MENTION_ID" NVARCHAR(128) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "DOCUMENT_ID" NVARCHAR(64),
    "ENTITY_ID" NVARCHAR(128) NOT NULL,
    "CHUNK_ID" NVARCHAR(128) NOT NULL,
    "SURFACE_TEXT" NVARCHAR(1000),
    "START_OFFSET" INTEGER,
    "END_OFFSET" INTEGER,
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("TENANT_ID", "MENTION_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_CHECK_RESULTS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_CHECK_RESULTS" (
    "RESULT_ID" NVARCHAR(64) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "RECORD_ID" NVARCHAR(128) NOT NULL,
    "SCORE" DOUBLE NOT NULL,
    "CANDIDATES_JSON" NCLOB,
    "DECISION_TRACE_JSON" NCLOB,
    "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP,
    PRIMARY KEY ("TENANT_ID", "RESULT_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_BACKGROUND_JOBS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_BACKGROUND_JOBS" (
    "JOB_ID" NVARCHAR(64) NOT NULL,
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "STATUS" NVARCHAR(32) NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP,
    "STARTED_AT" TIMESTAMP,
    "ENDED_AT" TIMESTAMP,
    "ERROR_MESSAGE" NCLOB,
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("TENANT_ID", "JOB_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_FILE_SYNC_STATE'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_FILE_SYNC_STATE" (
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "FILE_ID" NVARCHAR(512) NOT NULL,
    "SOURCE_UPDATED_AT" TIMESTAMP,
    "LAST_INDEXED_AT" TIMESTAMP,
    "PARSE_STATUS" NVARCHAR(64),
    "CONTENT_HASH" NVARCHAR(128),
    "METADATA_JSON" NCLOB,
    PRIMARY KEY ("TENANT_ID", "FILE_ID")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_HEADER_MAPPING_CACHE'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_HEADER_MAPPING_CACHE" (
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "CACHE_KEY" NVARCHAR(512) NOT NULL,
    "FILE_ID" NVARCHAR(512),
    "HEADER_SIGNATURE" NVARCHAR(512),
    "MAPPING_JSON" NCLOB,
    "METADATA_JSON" NCLOB,
    "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_UTCTIMESTAMP,
    PRIMARY KEY ("TENANT_ID", "CACHE_KEY")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_DOCUMENTS_TENANT_ID'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_DOCUMENTS_TENANT_ID" ON "AE_RAG_DOCUMENTS" ("TENANT_ID")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_DOCUMENTS_STATUS'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_DOCUMENTS_STATUS" ON "AE_RAG_DOCUMENTS" ("STATUS")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNKS_TENANT_ID'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_CHUNKS_TENANT_ID" ON "AE_RAG_CHUNKS" ("TENANT_ID")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNKS_DOCUMENT_ID'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_CHUNKS_DOCUMENT_ID" ON "AE_RAG_CHUNKS" ("DOCUMENT_ID")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNKS_STATUS'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_CHUNKS_STATUS" ON "AE_RAG_CHUNKS" ("STATUS")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_PARENT_CONTEXTS_TENANT_ID'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_PARENT_CONTEXTS_TENANT_ID" ON "AE_RAG_PARENT_CONTEXTS" ("TENANT_ID", "DOCUMENT_ID")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_GRAPH_ENTITIES_NAME'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_GRAPH_ENTITIES_NAME" ON "AE_RAG_GRAPH_ENTITIES" ("TENANT_ID", "NORMALIZED_NAME")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_BACKGROUND_JOBS_STATUS'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_BACKGROUND_JOBS_STATUS" ON "AE_RAG_BACKGROUND_JOBS" ("TENANT_ID", "STATUS", "UPDATED_AT")';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNKS_EMBEDDING'
) THEN EXECUTE IMMEDIATE 'CREATE HNSW VECTOR INDEX "AE_IDX_RAG_CHUNKS_EMBEDDING" ON "AE_RAG_CHUNKS" ("EMBEDDING") SIMILARITY FUNCTION COSINE_SIMILARITY';
END IF;
END;
