DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_SERVICE_CONFIGURATIONS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_SERVICE_CONFIGURATIONS" (
    "KEY" NVARCHAR(255) NOT NULL,
    "VALUE" NCLOB NOT NULL,
    PRIMARY KEY ("KEY")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SEARCH_FUZZY_THRESHOLD'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SEARCH_FUZZY_THRESHOLD'', ''0.8'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'VECTOR_SEARCH_TOP_K'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''VECTOR_SEARCH_TOP_K'', ''10'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'VECTOR_MIN_SCORE'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''VECTOR_MIN_SCORE'', ''0.45'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'DUPLICATE_GRAPH_SCORE_WEIGHT'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''DUPLICATE_GRAPH_SCORE_WEIGHT'', ''0.08'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SEARCH_MAX_RESULTS'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SEARCH_MAX_RESULTS'', ''10'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SEARCH_EXPAND_TERMS_ENABLED'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SEARCH_EXPAND_TERMS_ENABLED'', ''false'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SIMILARITY_GRAPH_SEED_TOP_K'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SIMILARITY_GRAPH_SEED_TOP_K'', ''8'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SIMILARITY_GRAPH_NEIGHBOR_CAP_PER_SEED'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SIMILARITY_GRAPH_NEIGHBOR_CAP_PER_SEED'', ''6'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SIMILARITY_GRAPH_MAX_RELATION_CANDIDATES'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SIMILARITY_GRAPH_MAX_RELATION_CANDIDATES'', ''24'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SIMILARITY_GRAPH_MAX_GRAPH_CHUNK_CANDIDATES'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SIMILARITY_GRAPH_MAX_GRAPH_CHUNK_CANDIDATES'', ''16'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'SIMILARITY_MAX_RESULTS'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''SIMILARITY_MAX_RESULTS'', ''10'')
';
END IF;
END;

-- SA-1474: material SDS source config (JSON-encoded lists; global scope).
DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'MATERIAL_SDS_RESOURCE_URLS'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''MATERIAL_SDS_RESOURCE_URLS'', ''["https://pubchem.ncbi.nlm.nih.gov", "https://echa.europa.eu", "https://www.osha.gov"]'')
';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM "AE_SERVICE_CONFIGURATIONS"
    WHERE "KEY" = 'MATERIAL_SDS_ALLOWED_DOMAINS'
) THEN EXECUTE IMMEDIATE '
INSERT INTO "AE_SERVICE_CONFIGURATIONS" ("KEY", "VALUE")
VALUES (''MATERIAL_SDS_ALLOWED_DOMAINS'', ''["pubchem.ncbi.nlm.nih.gov", "echa.europa.eu", "osha.gov"]'')
';
END IF;
END;
