DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.TABLES
    WHERE TABLE_NAME = 'AE_RAG_CHUNK_SEARCH_FIELDS'
) THEN EXECUTE IMMEDIATE '
CREATE COLUMN TABLE "AE_RAG_CHUNK_SEARCH_FIELDS" (
    "TENANT_ID" NVARCHAR(64) NOT NULL,
    "DOCUMENT_ID" NVARCHAR(64) NOT NULL,
    "CHUNK_ID" NVARCHAR(128) NOT NULL,
    "ROW_NUMBER" INTEGER,
    "FIELD_NAME" NVARCHAR(255) NOT NULL,
    "FIELD_VALUE" NCLOB NOT NULL,
    "NORMALIZED_FIELD_VALUE" NCLOB NOT NULL,
    "NORMALIZED_FIELD_HASH" NVARCHAR(64) NOT NULL,
    PRIMARY KEY ("TENANT_ID", "CHUNK_ID", "FIELD_NAME")
)';
END IF;
END;

DO BEGIN IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNK_SEARCH_FIELDS_LOOKUP'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_CHUNK_SEARCH_FIELDS_LOOKUP" ON "AE_RAG_CHUNK_SEARCH_FIELDS" ("TENANT_ID", "FIELD_NAME", "NORMALIZED_FIELD_HASH")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNK_SEARCH_FIELDS_DOC'
) THEN EXECUTE IMMEDIATE 'CREATE INDEX "AE_IDX_RAG_CHUNK_SEARCH_FIELDS_DOC" ON "AE_RAG_CHUNK_SEARCH_FIELDS" ("TENANT_ID", "DOCUMENT_ID")';
END IF;
IF NOT EXISTS (
    SELECT 1
    FROM SYS.INDEXES
    WHERE INDEX_NAME = 'AE_IDX_RAG_CHUNK_SEARCH_FIELDS_FUZZY'
) THEN EXECUTE IMMEDIATE 'CREATE FUZZY SEARCH INDEX AE_IDX_RAG_CHUNK_SEARCH_FIELDS_FUZZY ON "AE_RAG_CHUNK_SEARCH_FIELDS"("NORMALIZED_FIELD_VALUE") SEARCH MODE TEXT;';
END IF;
END;
